const peopleList = [
  {
    email: 'gingras@lunenfeld.ca',
    file: 'anneclaude-gingras',
    name: 'Anne-Claude Gingras',
    title: 'Principal investigator',
  },
  {
    email: 'bkhatri@lunenfeld.ca',
    file: 'bhavisha-khatri',
    name: 'Bhavisha Khatri',
    title: 'Lab manager',
  },
  {
    email: 'hesketh@lunenfeld.ca',
    file: 'geoff-hesketh',
    name: 'Geoffrey Hesketh',
    title: 'Postdoctoral fellow',
  },
  {
    email: 'clmartin@lunenfeld.ca',
    file: 'claire-martin',
    name: 'Claire Martin',
    title: 'Postdoctoral fellow',
  },
  {
    email: 'go@lunenfeld.ca',
    file: 'chris-go',
    name: 'Chris Go',
    title: 'Graduate student',
  },
  {
    email: 'jon.roth@mail.utoronto.ca',
    file: 'jonathan-roth',
    name: 'Jonathan Roth',
    title: 'Graduate student',
  },
  {
    email: 'bdyakov@lunenfeld.ca',
    file: 'boris-dyakov',
    name: 'Boris Dyakov',
    title: 'Graduate student',
  },
  {
    email: 'rsamson@lunenfeld.ca',
    file: 'reuben-samson',
    name: 'Reuben Samson',
    title: 'Graduate student',
  },
  {
    email: 'kabe@lunenfeld.ca',
    file: 'kento-abe',
    name: 'Kento Abe',
    title: 'Graduate student',
  },
  {
    email: 'shimon.rosenthal@mail.utoronto.ca',
    file: 'shimon-rosenthal',
    name: 'Shimon Rosenthal',
    title: 'Graduate student',
  },
  {
    email: 'fzangari@lunenfeld.ca',
    file: 'francesco-zangari',
    name: 'Francesco Zangari',
    title: 'Graduate student',
  },
  {
    email: 'jkitaygorodsky@lunenfeld.ca',
    file: 'julia-kitaygorodsky',
    name: 'Julia Kitaygorodsky',
    title: 'Graduate student',
  },
  {
    email: 'ralmismar@lunenfeld.ca',
    file: '',
    name: 'Rasha Al Mismar',
    title: 'Graduate student',
  },
  {
    email: 'asrinivasan@lunenfeld.ca',
    file: '',
    name: 'Aparna Srinivasan',
    title: 'Graduate student',
  },
  {
    email: 'ngrinberg@lunenfeld.ca',
    file: '',
    name: 'Nicolas Grinberg',
    title: 'Graduate student',
  },
  {
    email: 'mfazel@lunenfeld.ca',
    file: '',
    name: 'Mahya Fazel',
    title: '',
  },
  {
    email: 'jknight@lunenfeld.ca',
    file: 'james-knight',
    name: 'James Knight',
    title: 'Bioinformatician',
  },
  {
    email: 'gliu@lunenfeld.ca',
    file: 'frank-liu',
    name: 'Frank Liu',
    title: 'Programmer',
  },
  {
    email: 'jpzhang@lunenfeld.ca',
    file: 'jianping-zhang',
    name: 'Jian-Ping Zhang',
    title: 'Programmer',
  },
  {
    email: 'larsen@lunenfeld.ca',
    file: 'brett-larsen',
    name: 'Brett Larsen',
    title: 'Mass spectrometry coordinator',
  },
  {
    email: 'cwong@lunenfeld.ca',
    file: 'cassandra-wong',
    name: 'Cassandra Wong',
    title: 'Mass spectrometry technician',
  },
  {
    email: 'colwill@lunenfeld.ca',
    file: 'karen-colwill',
    name: 'Karen Colwill',
    title: 'Manager, NBCC',
  },
  {
    email: 'bseale@lunenfeld.ca',
    file: 'brendon-seale',
    name: 'Brendon  Seale',
    title: 'Research associate',
  },
  {
    email: 'zlin@lunenfeld.ca',
    file: 'zhenyuan-lin',
    name: 'Zhen-Yuan Lin',
    title: 'Research technician',
  },
  {
    email: 'qhu@lunenfeld.ca',
    file: 'queenie-hu',
    name: 'Queenie Hu',
    title: 'Research technician',
  },
  {
    email: '',
    file: '',
    name: 'Monica Dayam',
    title: '',
  },
  {
    email: '',
    file: '',
    name: 'Rod Hardy',
    title: '',
  },
];

export default peopleList;
