const peopleList = [
  {
    email: 'gingras@lunenfeld.ca',
    file: 'anneclaude-gingras',
    name: 'Anne-Claude Gingras',
    title: 'Principal investigator',
  },
  {
    email: 'colwill@lunenfeld.ca',
    file: 'karen-colwill',
    name: 'Karen Colwill',
    title: 'Manager, NBCC',
  },
  {
    email: 'rkalloush@lunenfeld.ca',
    file: 'rawan-kalloush',
    name: 'Rawan Kalloush',
    title: 'Lab manager',
  },
  {
    email: 'lseifried@lunenfeld.ca',
    file: 'laurie-seifried',
    name: 'Laurie Seifried',
    title: 'CoVaRR-Net pillar coordinator',
  },
  {
    email: 'clmartin@lunenfeld.ca',
    file: 'claire-martin',
    name: 'Claire Martin',
    title: 'Postdoctoral fellow',
  },
  {
    email: 'udionne@lunenfeld.ca',
    file: 'ugo-dionne',
    name: 'Ugo Dionne',
    title: 'Postdoctoral fellow',
  },
  {
    email: 'jon.roth@mail.utoronto.ca',
    file: 'jonathan-roth',
    name: 'Jonathan Roth',
    title: 'Graduate student',
  },
  {
    email: 'bdyakov@lunenfeld.ca',
    file: 'boris-dyakov',
    name: 'Boris Dyakov',
    title: 'Graduate student',
  },
  {
    email: 'rsamson@lunenfeld.ca',
    file: 'reuben-samson',
    name: 'Reuben Samson',
    title: 'Graduate student',
  },
  {
    email: 'kabe@lunenfeld.ca',
    file: 'kento-abe',
    name: 'Kento Abe',
    title: 'Graduate student',
  },
  {
    email: 'shimon.rosenthal@mail.utoronto.ca',
    file: 'shimon-rosenthal',
    name: 'Shimon Rosenthal',
    title: 'Graduate student',
  },
  {
    email: 'fzangari@lunenfeld.ca',
    file: 'francesco-zangari',
    name: 'Francesco Zangari',
    title: 'Graduate student',
  },
  {
    email: 'jkitaygorodsky@lunenfeld.ca',
    file: 'julia-kitaygorodsky',
    name: 'Julia Kitaygorodsky',
    title: 'Graduate student',
  },
  {
    email: 'ralmismar@lunenfeld.ca',
    file: 'rasha-mismar',
    name: 'Rasha Al Mismar',
    title: 'Graduate student',
  },
  {
    email: 'asrinivasan@lunenfeld.ca',
    file: 'aparna-srinivasan',
    name: 'Aparna Srinivasan',
    title: 'Graduate student',
  },
  {
    email: 'ngrinberg@lunenfeld.ca',
    file: 'nicolas-grinberg',
    name: 'Nicolas Grinberg',
    title: 'Graduate student',
  },
  {
    email: 'bahmed@lunenfeld.ca',
    file: 'raktan-ahmed',
    name: 'Raktan Ahmed',
    title: 'Graduate student',
  },
  {
    email: 'bmohamed@lunenfeld.ca',
    file: '',
    name: 'Bilan Mohamed',
    title: 'Graduate student',
  },
  {
    email: 'fqi@lunenfeld.ca',
    file: '',
    name: 'Freda Qi',
    title: 'Bioinformatics specialist',
  },
  {
    email: 'gliu@lunenfeld.ca',
    file: 'frank-liu',
    name: 'Frank Liu',
    title: 'Programmer',
  },
  {
    email: 'jpzhang@lunenfeld.ca',
    file: 'jianping-zhang',
    name: 'Jian-Ping Zhang',
    title: 'Programmer',
  },
  {
    email: 'larsen@lunenfeld.ca',
    file: 'brett-larsen',
    name: 'Brett Larsen',
    title: 'Mass spectrometry coordinator',
  },
  {
    email: 'cwong@lunenfeld.ca',
    file: 'cassandra-wong',
    name: 'Cassandra Wong',
    title: 'Mass spectrometry technician',
  },
  {
    email: 'bseale@lunenfeld.ca',
    file: 'brendon-seale',
    name: 'Brendon  Seale',
    title: 'Research associate',
  },
  {
    email: 'qhu@lunenfeld.ca',
    file: 'queenie-hu',
    name: 'Queenie Hu',
    title: 'Research associate',
  },
  {
    email: 'rdayam@lunenfeld.ca',
    file: 'monica-dayam',
    name: 'Monica Dayam',
    title: 'Research associate',
  },
  {
    email: 'whardy@lunenfeld.ca',
    file: 'rod-hardy',
    name: 'Rod Hardy',
    title: 'CoVaRR-Net research associate',
  },
  {
    email: 'zlin@lunenfeld.ca',
    file: 'zhenyuan-lin',
    name: 'Zhen-Yuan Lin',
    title: 'Research technician',
  },
  {
    email: 'gmailhot@lunenfeld.ca',
    file: 'genevieve-mailhot',
    name: 'Geneviève Mailhot',
    title: 'Research technician',
  },
  {
    email: 'delgadobrand@lunenfeld.ca',
    file: '',
    name: 'Melanie Delgado-Brand',
    title: 'Research technician',
  },
  {
    email: 'ttursun@lunenfeld.ca',
    file: '',
    name: 'Tulunay Tursun',
    title: 'Research technician',
  },
  {
    email: '',
    file: '',
    name: 'Alexandra Kurtesi',
    title: 'Student research assistant',
  }
];

export default peopleList;
